### ISSUE TITLE
CI: Tests on Windows are broken

### ISSUE THREAD

**Issue by stlankes** [hermitcore/libhermit-rs#122]
Currently, Qemu isn't working on Windows, which we install via chocolatey.

@jschwe Do you have an idea to solve it?

**Comment by jschwe** [comment]
Looks like qemu  (qemu-system-x86_64) isn't in PATH.
I'll investigate where chocolatey is installing it.

**Comment by jschwe** [comment]
So a short update from me: Chocolatey seems to install Qemu into `"C:\Program Files (x86)\qemu` now. 
There seems to be something else broken though since updating the Path doesn't fix the failure. 
Running `& "C:\Program Files (x86)\qemu\qemu-system-x86_64.exe" -version` gives an error in the Github action when it should be printing the version information (works fine on my system). The executable is definitely there, though.
