### ISSUE TITLE
support of bootimage

### ISSUE THREAD

**Issue by stlankes** [hermitcore/libhermit-rs#16]
Build a bootable image with [bootimage](https://github.com/rust-osdev/bootimage). Bootimage use a boot loader, which is better maintained in comparison to our own.

**Comment by jschwe** [comment]
Switching to the bootloader provided by bootimage means that the entrypoint changes from `_start(boot_info: &'static mut BootInfo)` to `_start(boot_info: &'static bootloader::bootinfo::BootInfo)`
Since [bootloader::bootinfo::BootInfo](https://docs.rs/bootloader/0.8.9/bootloader/bootinfo/struct.BootInfo.html) passes less information, some of the detection must move to the kernel.
```
pub struct BootInfo {
	pub magic_number: u32,
	pub version: u32,
	pub base: u64,
	pub limit: u64,
	pub image_size: u64,
	pub tls_start: u64,
	pub tls_filesz: u64,
	pub tls_memsz: u64,
	pub current_stack_address: u64,
	pub current_percore_address: u64,
	pub host_logical_addr: u64,
	pub boot_gtod: u64,
	pub mb_info: u64,
	pub cmdline: u64,
	pub cmdsize: u64,
	pub cpu_freq: u32,
	pub boot_processor: u32,
	pub cpu_online: u32,
	pub possible_cpus: u32,
	pub current_boot_id: u32,
	pub uartport: u16,
	pub single_kernel: u8,
	pub uhyve: u8,
	pub hcip: [u8; 4],
	pub hcgateway: [u8; 4],
	pub hcmask: [u8; 4],
}
```

Is any information definitely lost, or can everything be integrated on the kernel side?
From what I've looked into we lose multiboot, since bootimage doesn't seem to support that (yet). This could be an issue because e.g. cmdline relies on that. 

Since I've just started looking into this, I'd like to here your opinions if there is something important that would break and can't be moved to the kernel for whatever reason.

**Comment by stlankes** [comment]
Your are right, using bootimage is more complicated than I thought. Interpreting the ELF file and determining the [thread local storage](https://github.com/hermitcore/rusty-loader/blob/master/src/lib.rs#L92-L101) is important.

In principle, I like our boot loader, but [move_kernel](https://github.com/hermitcore/rusty-loader/blob/master/src/arch/x86_64/mod.rs#L114) is a dirty hack. I copy the data in [reverse](https://github.com/hermitcore/rusty-loader/blob/master/src/arch/x86_64/mod.rs#L131) direction. This is bad for the boot time.

By the way, these [hints](https://github.com/bonzini/qboot) are also useful.

**Comment by stlankes** [comment]
Hm, I move the kernel always to the suggested virtual address, which is encoded in the ELF file. However, the application should be completely [moveable](https://github.com/rust-lang/rust/blob/master/src/librustc_target/spec/hermit_kernel_base.rs#L19). Maybe the identity mapping isn't required.

**Comment by stlankes** [comment]
The kernel is now moveable. @jschwe Do we need bootimage support? I like the current boot loader.
