### ISSUE TITLE
Support of Qemu's MicroVM

### ISSUE THREAD

**Issue by stlankes** [hermitcore/libhermit-rs#161]
As alternative to uhyve, we should als support [Qemu's MicroVM](https://qemu.readthedocs.io/en/latest/system/i386/microvm.html). Currently, it isn't runnable. I think that the initialization of the interrupt controller failed.

**Comment by mkroening** [comment]
This broke between [run 1657712283](https://github.com/hermitcore/libhermit-rs/actions/runs/1657712283) (2022-01-05T10:39 GTM+1) and  [run 1657809671](https://github.com/hermitcore/libhermit-rs/actions/runs/1657809671) (2022-01-05T11:05 GTM+1) due to external circumstances (Ubuntu packages?). This is not caused by any change between these runs, since the behavior is reproducible in reruns of the current master commit: [run 1646587929 attempt 2](https://github.com/hermitcore/libhermit-rs/actions/runs/1646587929/attempts/2) vs [run 1646587929 attempt 3](https://github.com/hermitcore/libhermit-rs/actions/runs/1646587929/attempts/3).

**Comment by stlankes** [comment]
Our CI is testing the microvm and seems to work.
