### ISSUE TITLE
CI failed because it used an old version of our loader

### ISSUE THREAD

**Issue by stlankes** [hermitcore/libhermit-rs#55]
At least PR #54 failed because the CI used an old version of our loader. @jschwe Do you have an idea, why this happens?

**Comment by jschwe** [comment]
The log shows: `error: legacy asm! syntax is no longer supported`
Is it not possible to use a current version of the loader? The error occurs in the x86 crate (version 0.20) and probably is not an issue in current versions.

**Comment by stlankes** [comment]
No, I changed it (see commit [rusty-loader](https://github.com/hermitcore/rusty-loader/commit/c73345d98f6adfeb72f58dd2da4ec91314b66ba0)). I think that the CI use an old version of the loader. But I have no clue why...

**Comment by jschwe** [comment]
The log says:` Submodule path 'loader': checked out '8f2b492b77f0898465449c04aa3c1307043bb0d8'`. That is the expected commit (and current).
The error is also not in the loader itself but in the dependency x86. 
The lock file in rusty-loader must be updated, since it requires `x86 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)`, which still contains the asm! instructions.

**Comment by stlankes** [comment]
Ah, such a simple solution :-)
